### ISSUE TITLE
Добавить контроль версии протокола сервером

### ISSUE THREAD

**Issue by rus-ai** [MoreliaTalk/morelia_server#116]
### Проблема
Иногда протокол существенно меняется, как например недавняя смена типа данных UUID, отловить это можно буде только по логам ошибок

### Решение
Для прозрачной диагностики: 
* расширить протокол добавить 505 ошибку по аналогии с http (версия протокола не поддерживается) 
* в сервере в модуле api прописать константы minClientVersion и maxClientVersion 
* при авторизации клиента с версией JSON вне интервала прекратить обслуживание клиента сообщив ему в расширенном описании ошибки необходимые версии. 

### Дополнительно
Версию протокола до полной реализации я предложил бы в Json понизить до 0.9.xxx

**Comment by xIMRANx** [comment]
Предлагаю вместо прописывания минимальной и максимальной версии протокола, сделать список совместимых версий протокола с текущей, т.к:
Протокол может меняться и откатыватся обратно, то есть, если мы в версии 1.0.1.17 изменим протокол, а в версии 1.0.1.18 вернём его в примерно то же состояние что и в 1.0.1.16, версия 1.0.1.16 все равно будет считаться устарелой, хотя по сути она полностью будет совместима

**Comment by stepanskryabin** [comment]
> Предлагаю вместо прописывания минимальной и максимальной версии протокола, сделать список совместимых версий протокола с текущей, т.к: Протокол может меняться и откатыватся обратно, то есть, если мы в версии 1.0.1.17 изменим протокол, а в версии 1.0.1.18 вернём его в примерно то же состояние что и в 1.0.1.16, версия 1.0.1.16 все равно будет считаться устарелой, хотя по сути она полностью будет совместима

А где этот список будет находится? И как поддерживаться его актуальность?

**Comment by xIMRANx** [comment]
Хранить будем в конфиге, актуальность будем поддерживать добавлением версии протокола в ручную

**Comment by stepanskryabin** [comment]
> Хранить будем в конфиге, актуальность будем поддерживать добавлением версии протокола в ручную

Правильно ли я понял, что ты просто предлагаешь вместо списка из двух элементов (мин. и макс. версии протокола) - предлагаешь хранить список всех совместимых версий?

**Comment by xIMRANx** [comment]
да

> > Хранить будем в конфиге, актуальность будем поддерживать добавлением версии протокола в ручную
> 
> Правильно ли я понял, что ты просто предлагаешь вместо списка из двух элементов (мин. и макс. версии протокола) - предлагаешь хранить список всех совместимых версий?

да

**Comment by stepanskryabin** [comment]
Тогда, давай реализуй в коде )))
