### ISSUE TITLE
Сменить нумерацию версий

### ISSUE THREAD

**Issue by stepanskryabin** [MoreliaTalk/morelia_server#142]
Сейчас готовится к выходу сервер версии 0.0.3. Такая нумерация не отражает развитие. Предлагаю изменить нумерацию, где версия 1.0 это стабильная версия сервера которая поддерживает 100% протокола и в которой реализованы все "базовые" фишки, типа шифрования и аутентификации через OAuth.

**Comment by NekrodNIK** [comment]
В принципе я с тобой согласен, однако внесу некоторые уточнения. Планируется смена нумерации на следующую схему: 1.2.3, где 1 это мажорная версия, еë выход означает глобальные изменения, 2 это минорная версия, которая может нести в себе как мелкие, так и глобальные изменения, а 3 - патчи. Следущей версией станет 0.3.0, и затем постепенно мы дойдëм до первого стабильного релиза 1.0.0
