### ISSUE TITLE
Документацию невозможно открыть по ссылке https://moreliatalk.github.io/morelia_server/

### ISSUE THREAD

**Issue by stepanskryabin** [MoreliaTalk/morelia_server#196]
Проблема в скрипте сборки документации

**Comment by NekrodNIK** [comment]
Это баг не в скрипте сборки, а в том, как у нас лежит документация. А лежит она у нвс в папках. И надо как-то сделать редирект на папку master

**Comment by NekrodNIK** [comment]
Исправлено. Добавил корень ветви docs index.html файл с редиректом на подпуть master

**Comment by stepanskryabin** [comment]
> Это баг не в скрипте сборки, а в том, как у нас лежит документация. А лежит она у нвс в папках. И надо как-то сделать редирект на папку master

А в скрипте сборки никак не поменять настройки чтобы он компилировал документацию не в директорию master а в корень репозитория docs?

**Comment by NekrodNIK** [comment]
А, стоп у нас же теперь ветви девелоп-то нет. Щас поправлю
