### ISSUE TITLE
Реализация методов протокола в одном классе(+ допилить все методы и протокол в целом)

### ISSUE THREAD

**Issue by NekrodNIK** [MoreliaTalk/morelia_server#36]
In process

**Comment by NekrodNIK** [comment]
В общем придумал взаимодействие сервера и клиента:
1)Клиент регистрируется или входит(делается один раз на новом устройстве или если на этом устройстве вышли)
2)При каждом заходе в клиент он аутенфицируется(проверяется его валидность)
3)При выборе определённого Flow клиент смотрит в свою бд и если там нет сообщений от него то он посылает запрос всех сообщений этого flow, иначе он запрашивает все сообщения по Id больших чем последнее полученное(да не по времени, по id точнее и проще)
4)Клиент ждёт сообщений от этого flow и сам их отправляет

**Comment by stepanskryabin** [comment]
а дескрипшон где?
