### ISSUE TITLE
Описание проекта, о чем он вообще?

### ISSUE THREAD

**Issue by david-shiko** [MoreliaTalk/morelia_server#83]
Добавьте пожалуйста о чем проект в принципе. 

Я нашел проект по запросу `fastapi messenger`. Я хочу написать мэссенджер аля телеграмм на fastapi + вебсокеты + postgres 

Запросу morelia выдает неоднозначную информацию.

**Comment by stepanskryabin** [comment]
а тут смотрел? https://github.com/MoreliaTalk/morelia_server/wiki#%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-moreliatalk
