### ISSUE TITLE
Добавить создание пользователя в manage.py

### ISSUE THREAD

**Issue by stepanskryabin** [MoreliaTalk/morelia_server#93]
Сейчас в manage.py создается пользователя с фиксированным паролем/логином и уже сгенерированным хэшем, необходимо сделать регистрацию пользователя с произвольным логином/паролем и с автоматической генерацией хэша.

**Comment by stepanskryabin** [comment]
При этом учитывать, что настроечные параметры из config.ini (секция SUPERUSER) в версии 0.3 будут удалены.

**Comment by NekrodNIK** [comment]
Ok, буду учитывать и не использовать их
